## Write a Numpy program to compute the multiplication of two given matrixes

In [1]:
import numpy as np

In [2]:
arr1=np.array([[1,2,3],
               [1,2,3]])

arr2=np.array([[1,2,3],
               [1,2,3]])
print(arr1*arr2)

[[1 4 9]
 [1 4 9]]


In [3]:
arr1=np.array([[1,2],
               [1,2]])

arr2=np.array([[1,2],
               [1,2]])

print(arr1.dot(arr2))

[[3 6]
 [3 6]]


## Write a NumPy program to compute the determinant of a given square array

In [4]:
arr = np.array([[1,4,5],
                [5,1,3],
                [1,7,8]])
res=np.linalg.det(arr)
res

8.99999999999997

## Write a NumPy program to compute the cross product of two given vectors

In [6]:
v1=np.array([2,3])
v2=np.array([1,7])
res = np.cross(v1,v2)
res

array(11)

## Write a NumPy program to compute the condition number of a given matrix

In [12]:
arr=np.array([[2,3],
              [1,7]])
np.linalg.cond(arr)

5.546994935117353

## Write a NumPy program to compute the inverse of a given matrix

In [11]:
arr=np.array([[2,3],
              [1,7]])
res=np.linalg.inv(arr)
res

array([[ 0.63636364, -0.27272727],
       [-0.09090909,  0.18181818]])